version: '3'

volumes:
  postgres16-data:
  pgadmin-data:
  redis-data:
  mailpit-data:

services:
  postgres16:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres16-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    environment:
      TZ: Europe/London
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - '1025:1025'
      - '8025:8025'
    volumes:
      - mailpit-data:/data
